# Generated by Django 5.0.4 on 2024-05-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='Contact',
        ),
    ]
