# Generated by Django 5.0.4 on 2024-05-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_upgrade_remove_usersubscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='access_level',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', max_length=10),
        ),
    ]
