# Generated by Django 5.0.4 on 2024-05-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_upgrade_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=10),
        ),
    ]
