# Generated by Django 5.0.4 on 2024-05-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
